server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: utf-8
cloud:
  aws:
    s3:
      bucket: myblog-s3
    credentials:
      accessKey: ${{ screts.BUCKETACCESS }}
      secretKey: ${{ screts.BUCKETSECRET }}
    region:
      static: us-east-1
    stack:
      auto: 'false'
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    password: password
    username: root
    url: jdbc:mysql://springboot-database.cqhormvrsfxj.us-east-1.rds.amazonaws.com:3306/myselectshop?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
jwt:
  secret: ${{ screts.JWTKEY }}
